version: "3.9"

networks:
  mysql:
    driver: bridge
    attachable: true
#  postgress:
#    driver: bridge
#    attachable: true

services:
  psy-quiz-db:
    image: mysql:latest
    container_name: psy-quiz-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=psy-quiz
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - "./volumes/mysql/db:/var/lib/mysql"
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8081:80
    links:
      - psy-quiz-db
    environment:
      PMA_HOST: fdb
      PMA_PORT: 3308
      PMA_ARBITRARY: 1
    networks:
      - mysql

  postgress-db:
    image: postgres
    container_name: psy-quiz-postgress-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=psy-quiz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "3308:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
#    networks:
#      - postgres

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    networks:
#      - postgres
