# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#      - name: Run Docker Compose
#        run: docker-compose up -d

      - uses: actions/checkout@v4
      - run: ls
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: project/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
#      - run: npm run psy-quiz-backend-build-prod
#      - run: npm run build --if-present
      - name: Run tests
        run: npm run test

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # - run: npx nx affected -t lint test build